/*
 * InstanceEditor.java
 *
 * Created on 19 December 2008, 15:03
 */

package simplemorph;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author  twak
 */
public class InstanceEditor extends javax.swing.JFrame 
{
    BodyPart bp;
    FeatureSet set;
    BPSUI bpsui;
    
    /** Creates new form InstanceEditor */
    public InstanceEditor() {
        initComponents();
        setSize(600,600);
        setVisible(true);
    }
    
     public InstanceEditor(BPSUI bpusi) {
        this();
        this.bpsui = bpusi;
    }
    
    public void setImage(String image)
    {
        try
        {
            BufferedImage bi = ImageIO.read( new File( image ) );
            imageUI1.setImage( bi );
            fileNameField.setText( image );
        } 
        catch ( IOException ex )
        {
            ex.printStackTrace();
        }
    }
    
    public void setBodyPart( BodyPart bp )
    {
        this.bp = bp;
        setImage(bp.image);
        imageUI1.setBodyPart( bp );
        nameField.setText( bp.name );
    }

    void setFeatureSet( FeatureSet fs )
    {
        this.set = fs;
        imageUI1.setFeatureSet( fs );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageUI1 = new simplemorph.ImageUI();
        jPanel1 = new javax.swing.JPanel();
        fileNameField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        javax.swing.GroupLayout imageUI1Layout = new javax.swing.GroupLayout(imageUI1);
        imageUI1.setLayout(imageUI1Layout);
        imageUI1Layout.setHorizontalGroup(
            imageUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        imageUI1Layout.setVerticalGroup(
            imageUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        getContentPane().add(imageUI1, java.awt.BorderLayout.CENTER);

        fileNameField.setText("jTextField1");
        fileNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameFieldActionPerformed(evt);
            }
        });

        loadButton.setText("load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("image file:");

        jLabel2.setText("instance name:");

        nameField.setText("jTextField1");
        nameField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nameFieldCaretUpdate(evt);
            }
        });
        nameField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nameFieldInputMethodTextChanged(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fileNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loadButton)
                    .addComponent(fileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        
        try
        {
            BufferedImage bi = ImageIO.read( new File( fileNameField.getText() ) );
            imageUI1.setImage( bi );
            bp.image = fileNameField.getText();
        } 
        catch ( IOException ex )
        {
            JOptionPane.showMessageDialog( this, "File not found :(");
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_loadButtonActionPerformed

    private void fileNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameFieldActionPerformed
        loadButtonActionPerformed(evt);
}//GEN-LAST:event_fileNameFieldActionPerformed

private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
//    bp.name = nameField.getText();
//    bpsui.repaintInstanceList();
}//GEN-LAST:event_nameFieldKeyTyped

private void nameFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nameFieldInputMethodTextChanged
bp.name = nameField.getText();
    bpsui.repaintInstanceList();
}//GEN-LAST:event_nameFieldInputMethodTextChanged

private void nameFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nameFieldCaretUpdate
bp.name = nameField.getText();
    bpsui.repaintInstanceList();
}//GEN-LAST:event_nameFieldCaretUpdate
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileNameField;
    private simplemorph.ImageUI imageUI1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
    
}
