/*
 * ShowImage.java
 *
 * Created on January 12, 2009, 10:03 PM
 */

package simplemorph;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author  tom
 */
public class ShowImage extends javax.swing.JFrame {

    BufferedImage image;
    /** Creates new form ShowImage */
    public ShowImage(BufferedImage image) {
        this.image = image;
        initComponents();
        setSize( image.getWidth(), image.getHeight()+20);
        setVisible( true );
    }

    @Override
    public void paint( Graphics g )
    {
        g.setColor( Color.gray);
        g.fillRect( 0,0,getWidth(), getHeight());
        g.drawImage( image, 0, 0, null );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
